// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB96mF97TPpEeKNrHXBfWoGU4V3wFh7y-A',
    appId: '1:1026648952458:web:be649a0444c36123362773',
    messagingSenderId: '1026648952458',
    projectId: 'chatnew-d42e2',
    authDomain: 'chatnew-d42e2.firebaseapp.com',
    storageBucket: 'chatnew-d42e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnnmnEJK1XEi0GQCG20ZxDvS_d2ongxDU',
    appId: '1:1026648952458:android:a118dbdd707d910f362773',
    messagingSenderId: '1026648952458',
    projectId: 'chatnew-d42e2',
    storageBucket: 'chatnew-d42e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoXMR7QsG-lm9HK2N0iPayWJcI0zdM8qo',
    appId: '1:1026648952458:ios:0f2d3126847a2010362773',
    messagingSenderId: '1026648952458',
    projectId: 'chatnew-d42e2',
    storageBucket: 'chatnew-d42e2.appspot.com',
    iosBundleId: 'com.example.chatnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoXMR7QsG-lm9HK2N0iPayWJcI0zdM8qo',
    appId: '1:1026648952458:ios:f2cf5e34219a024d362773',
    messagingSenderId: '1026648952458',
    projectId: 'chatnew-d42e2',
    storageBucket: 'chatnew-d42e2.appspot.com',
    iosBundleId: 'y',
  );
}
